### ISSUE TITLE
Conda package not installing

### ISSUE THREAD

**Issue by dnhkng** [allegroai/clearml-agent#76]
I am trying to use the agent to reproduce my local setup (that is built using conda). However, it does not install a vital package, which is "rdkit", found on conda-forge.

To start the agent I use:
` clearml-agent daemon --queue default`

I have modified the clearml.conf file with these changes:
 - added the `agent {...` section from the documentation
 - added: `type: conda,`
 - added `post_packages: ["rdkit", ]`

Looking at the console output in the WebUI, the last line is:
`Traceback (most recent call last):`
`  File "run.py", line 12, in <module>`
`import rdkit`
`ModuleNotFoundError: No module named 'rdkit'`

Scrolling higher up, I see:
`Conda: Trying to install requirements:`
`['pytorch~=1.9.0', 'graphviz', 'python-graphviz', 'kiwisolver']`

`Conda: Installing requirements: step 2 - using pip:`
`['clearml==1.0.5', 'matplotlib==3.4.3', 'git+https://github.com/lessw2020/Ranger21.git@0a906ef9df4a4c394a48e5778b2b94f2c8e1ce8e#egg=ranger21', 'torchvision==0.10.0', 'tqdm==4.62.2', 'x_transformers==0.16.1']`

So, it's not finding rdkit from the environment, the import in the main python script, or the clearml.conf file.  What should I try next?
I tried editing the "INSTALLED PACKAGES" in the "EXECUTION" section of the WebUI to add rdkit, but that seems to be for Pip. Can I force it to use conda there?

**Comment by bmartinn** [comment]
Hi @dnhkng 
A few questions:
1) Are both the "development" environment and the agent running conda?
2) Why do you have to always install the "rdkit" package by the agent ? How come it is not detected by the auto package discovery on the development environemnt
3) Is "rdkit" a conda package or a python package (i.e. installed with "conda install" or "pip install" ?
4) Did you try manually adding the missing package with `Task.add_requirements("rdkit")` ? (notice you have to call it Before you call `Task.init(...)`)

> I tried editing the "INSTALLED PACKAGES" in the "EXECUTION" section of the WebUI to add rdkit, but that seems to be for Pip. Can I force it to use conda there?

Yes, that is correct, if running with conda you cannot actually edit the Installed packages from the UI, as it actually stores the conda/pip combination you had on the development environment in two different sections, and the assumption is that conda will be able to resolve it by itself ...

**Comment by dnhkng** [comment]
Thanks for the reply. To answer your questions:

1) they are both on the same physical computers. I'm using the agent for the first time, so I'm trying to test how this works. As I have 2x RTX Titans in this develooment machine, I was hoping to use the web interface to schedule and monitor experiments easily (even though it's a local machine).

2) maybe I'm misunderstanding the question, but doesn't the agent build a fresh docker, so rdkit would always have to be added to the image?

3) it's installed with Conda. It's not in the module that imports clearml, but a module I import in the main script. However, I see all the scripts are parsed correctly by clearml (at least for the Pip requirements).  I tried importing rdkit in the main script (I just got it to print rdkit.__version__), but it that didn't help. This was done before instantiating the clearml task, could this be the issue?

4) I didn't see that command in the documents, I'll give it a go when I get back to the computer.

I'll update when I get the new command tested.

**Comment by bmartinn** [comment]
> As I have 2x RTX Titans in this develooment machine, I was hoping to use the web interface to schedule and monitor experiments easily (even though it's a local machine).

That is a great idea. The man caveat is that you have to decide whether you want the two GPUs allocated for the same Task, or you want a GPU per Task. Specifically for our example, you can spin a single instance of the agent, allocating both GPUs to every Task the agent pulls, or spin two agents, each one with its own GPU.

> but doesn't the agent build a fresh docker, so rdkit would always have to be added to the image?

You are correct, but in order for the agent to install the package inside the container, you either have the package listed in the "installed packages" section (which is fully compatible with requirements.txt format) or if you clear the  "installed packages" section, the agent will look for the requirements.txt file inside the git repository and use it.

> ... but a module I import in the main script. 

That is the culprit, clearml will automagically list al the directed modules you import. The assumption is that the module you are using will have its requirements parsed when the agent installs it (e.g. install tensorflow will implicitly install numpy because it is in the part of the tensorflow wheel requirements).
I suspect the issue is that the module you are importing did not list `rdkit` as a required package, hence it was not installed by the agent.
In order to solve the issue, you can:
- Add the missing  `rdkit` to the requirement section of your module
- Specify to clearml that it needs to add `rdkit` anyhow:
``` python
# Call Before the Task.init call
Task.add_requirements('rdkit')
```
- Tell ClearML to list the enitre conda/pip environment (instead of just the directly imported packages) Use this one with care, some python packages will not able to be installed in a different container / os
``` python
# Call Before the Task.init call
Task.force_requirements_env_freeze()
```

> I tried importing rdkit in the main script (I just got it to print rdkit.version), but it that didn't help. This was done before instantiating the clearml task, could this be the issue?

That should have worked... `rdkit` listed in the python packages when you run `pip freeze`

**Comment by dnhkng** [comment]
OK, I've had a go at this, and it's not working well.

```
# Call Before the Task.init call
Task.add_requirements('rdkit')
```

If I use this command, I see that it tries to install using Pip instead of Conda:

```
Conda: Installing requirements: step 2 - using pip:
['matplotlib==3.4.3', 'rdkit']
```

Unfortunately, 'rdkit' is only available on conda.

If I use the other command:

```
# Call Before the Task.init call
Task.force_requirements_env_freeze()
```
I get rdkit installed, but then the GPU is not detected.

I'm starting my agent with: 

`$ clearml-agent daemon --gpus all --queue default
`

and in my script:
`torch.cuda.is_available()`

returns False.

**Comment by bmartinn** [comment]
Nice @dnhkng !
I think we should make sure `add_requirements` will support conda packages as well as pip.
