### ISSUE TITLE
Poetry vs pip choosing algorithm

### ISSUE THREAD

**Issue by johnml1135** [allegroai/clearml-agent#78]
In the default clearml.conf, the poetry-pip choice is stated as:
`# poetry is used if pip selected and repository contains poetry.lock file`
Yet, the actual logic in the code is:
https://github.com/allegroai/clearml-agent/blob/5a080798cb4292e198948fbe16cba70136cb6bdf/clearml_agent/helper/package/poetry_api.py#L53-L54
and
https://github.com/allegroai/clearml-agent/blob/5a080798cb4292e198948fbe16cba70136cb6bdf/clearml_agent/helper/package/poetry_api.py#L113-L116

meaning, poetry will be used if poetry called out in the config (`["agent.package_manager.type"] == "poetry"` and the lock file exists and either `pyproject.toml` or `poetry.lock` exists in the root path.

I would prefer the "choose poetry if there is the right file" as specified in the clearml.conf defualt file - but either way, one needs to be updated.

**Comment by bmartinn** [comment]
> # poetry is used if pip selected and repository contains poetry.lock file

Hmm this sounds like incorrect documentation :) 

> meaning, poetry will be used if poetry called out in the config (["agent.package_manager.type"] == "poetry" and the lock file exists and either pyproject.toml or poetry.lock exists in the root path.

Correct :)

> I would prefer the "choose poetry if there is the right file" as specified in the clearml.conf default file - but either way, one needs to be updated.

Okay let's fix the documentation, then "poetry"/"pip" is basically setting the package manager to "poetry" and then if the repo does not contain lock files, it will revert to pip.

Am I missing anything ?

**Comment by johnml1135** [comment]
Is there value in the switch at all?  Why not just have "if there is a lock/toml file, use it" - would the same logic work for conda?  Can you know from the files in the environment that you are supposed to use conda?  Can we remove the parameter completely?

**Comment by bmartinn** [comment]
>  Why not just have "if there is a lock/toml file, use it"

Well it's about control, we should have a way to tell the agent Not to use poetry (which means using pip only), then if we do select Poetry as a package manager, we basically select: "use poetry when possible, otherwise revert to pip". Make sense ?

> Would the same logic work for conda?
> Can you know from the files in the environment that you are supposed to use conda

There is a conda environment yaml file that is equivalent to a poetry lock file, but there is no standard name for it (at least that I'm aware of).
My issue with the auto detection is that usually this is a company wide policy, otherwise it can fail very quickly. Conda unfortunately is not a stable solution to restore environments (even though it is getting better), the easiest and most stable solution is containers + pip (poetry is great, but it can be very slow to install and users tend to forget to update it, hence the auto python package detection clearml does for you). wdyt ?

**Comment by johnml1135** [comment]
That is fine for our needs. Explicitly calling out poetry is a workable
solution. Thanks.
