### ISSUE TITLE
How to change setuptools version?

### ISSUE THREAD

**Issue by blackDZS** [allegroai/clearml-agent#97]
I want to use setuptools==59.5.0 with python=3.8, but the env created default using setuptools==60.6.0
`
created virtual environment CPython3.8.3.final.0-64 in 89ms
  creator CPython3Posix(dest=/data/home/ai/.clearml/venvs-builds/3.8, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/data/home/ai/.local/share/virtualenv)
    added seed packages: pip==22.0.3, setuptools==60.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
`

I have tried adding priority_packages to config file like this:
`priority_packages: ["setuptools==59.5.0",]`
but it doesn‘t work

**Comment by jkhenning** [comment]
Hi @blackDZS ,

Where did you set `priority_packages`?

**Comment by jkhenning** [comment]
Also, are you using ClearML Agent? What is your system setup?

**Comment by jkhenning** [comment]
Hi @blackDZS ,

I see you're using the ClearML agent in the venv mode (i.e. the agent will create a venv using your system python). What is the `setuptools` version in your system python?

**Comment by blackDZS** [comment]
@jkhenning My setuptools is 41.2.0

**Comment by blackDZS** [comment]
@jkhenning I test `mkvirtualenv` in my computer 

1. When I use `mkvirtualenv test` I get `setuptools==60.5.0`
2. When I use `mkvirtualenv test --no-setuptools` I get the env without setuptools
3. When I use `mkvirtualenv test --setuptools 59.5.0` I get the  `setuptools==59.5.0`, that's right!

Is there any way to control how to create the env?

**Comment by jkhenning** [comment]
Hi @blackDZS ,

> When I use mkvirtualenv test --setuptools 59.5.0 I get the setuptools==59.5.0, that's right!

That's a very interesting idea, and we might add that support for that.


Another thing you can do is create a suitable virtualenv and instruct the agent to use it instead of creating a new one, using the `CLEARML_AGENT_SKIP_PIP_VENV_INSTALL` environment variable which can simply provide the path to the python executable the agent should use for running the task. This is best used in the docker mode, by creating a docker image with a suitable venv, and instructing the agent to use that docker image with a direct reference to the python executable in the image that should be used.

**Comment by blackDZS** [comment]
@jkhenning Thanks for your answer, that solved my probelm !

**Comment by jkhenning** [comment]
@blackDZS cool!

By the way, you cal maybe also try to add this requirement specifically with `Task.add_requirements()`
